FROM ubuntu:20.04
LABEL maintainer=kral2
LABEL version="0.2.0"

WORKDIR /app
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    net-tools \
    openconnect \
    squid3 \
    dnsutils \
    && rm -rf /var/lib/apt/lists/*
COPY squid.conf /etc/squid/squid.conf
COPY entrypoint.sh ./entrypoint.sh
COPY mysecret.txt ./mysecret.txt
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ./entrypoint.sh
